# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 923b7be8b0ec626dafeed60446b21755f0b958d0f339c07aa073b433d42f7496806a2cd40a9abe17dfb02aefae3de6c89c6a1490b6df4f44963f70278fe40e15

test:
  secret_key_base: 0db21e60ca71946ea8b8ce2c4084c2992c9ea800102f0a7b80723b656227a6b7744ebd4fa553cdd2d19e99d1feb23bf2c26e4826b057d438f12252c17667871c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
